**Цель работы:**

Осуществить предварительную обработку данных csv-файла, выявить и устранить проблемы в этих данных.

# Загрузка набора данных

### Описание предметной области

Вариант №9

Набор данных: auto.csv

Атрибуты:
1. имя
2. год
3. цена продажи
4. пройдено км
5. топливо
6. тип продавца
7. коробка передач
8. тип владельца

### 1.Чтение файла (набора данных)

In [1]:
# импорт библиотек, чтение файла с помощью pandas
import pandas as pd
import numpy as np

# загрузка CSV-файла
df = pd.read_csv(r'D:\Jupyter_projects\ad_labs\auto.csv')

### 2. Обзор данных

2.1 Вывод первых 20 строк с помощью метода head.

In [2]:
df_clean = df.copy()

In [3]:
# применить метод head
print("Первые строки датафрейма:")
display(df.head(20))

Первые строки датафрейма:

,Name,year,SellingPrice,kmdriven,fuel,seller_Type,transmission,owner
0,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner
5,Maruti Alto LX BSIII,2007,140000.0,125000.0,Petrol,Individual,Manual,First Owner
6,Hyundai Xcent 1.2 Kappa S,2016,550000.0,25000.0,Petrol,Individual,Manual,First Owner
7,Tata Indigo Grand Petroll,2014,240000.0,60000.0,Petrol,Individual,Manual,Second Owner
8,Hyundai Creta 1.6 VTVT S,2015,850000.0,25000.0,Petroll,Individual,Manual,First Owner
9,Maruti Celerio Green VXI,2017,365000.0,78000.0,CNG,Individual,Manual,First Owner
10,Chevrolet Sail 1.2 Base,2015,260000.0,35000.0,Petrol,Individual,Manual,First Owner
11,Tata Indigo Grand Petrol,2014,250000.0,100000.0,Petrol,Individual,Manual,First Owner
12,Toyota Corolla Altis 1.8 VL CVT,2018,1650000.0,25000.0,Petrol,Dealer,Automatic,First Owner
13,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
14,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
15,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
16,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
17,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner
18,Maruti Alto LX BSIII,2007,140000.0,125000.0,Petrol,Individual,Manual,First Owner
19,Hyundai Xcent 1.2 Kappa S,2016,550000.0,25000.0,Petrol,Individual,Manual,First Owner

2.2 Оценка данных с помощью метода info.

In [4]:
# выполнит метод info
print("\nИнформация о датафрейме:")
df.info()

Информация о датафрейме:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4344 entries, 0 to 4343
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          4344 non-null   object
 1   year          4344 non-null   int64
 2   SellingPrice  4342 non-null   float64
 3   kmdriven      4343 non-null   float64
 4   fuel          4343 non-null   object
 5   seller_Type   4344 non-null   object
 6   transmission  4344 non-null   object
 7   owner         4344 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 271.6+ KB

2.3 Оценка данных с помощью метода describe.

In [5]:
# оцените числовые столбцы с помощью describe
print("Статистическое описание числовых признаков:")
display(df.describe())

Статистическое описание числовых признаков:

              year  SellingPrice       kmdriven
count  4344.000000  4.342000e+03    4343.000000
mean   2013.092311  5.039987e+05   66193.063320
std       4.214543  5.784465e+05   46636.648764
min    1992.000000  2.000000e+04       1.000000
25%    2011.000000  2.100000e+05   35000.000000
50%    2014.000000  3.500000e+05   60000.000000
75%    2016.000000  6.000000e+05   90000.000000
max    2020.000000  8.900000e+06  806599.000000

In [6]:
# переименование при необходимости
df_clean.columns = ['name', 'year', 'price', 'mileage', 'fuel', 'seller', 'transmission', 'owner']

In [7]:
# Убираем выбросы в SellingPrice через IQR
Q1_price = df_clean['price'].quantile(0.25)
Q3_price = df_clean['price'].quantile(0.75)
IQR_price = Q3_price - Q1_price

df_clean = df_clean[(df_clean['price'] >= Q1_price - 1.5*IQR_price) &
                    (df_clean['price'] <= Q3_price + 1.5*IQR_price)]

In [8]:
# Убираем выбросы в kmdriven через IQR
Q1_km = df_clean['mileage'].quantile(0.25)
Q3_km = df_clean['mileage'].quantile(0.75)
IQR_km = Q3_km - Q1_km

df_clean = df_clean[(df_clean['mileage'] >= Q1_km - 1.5*IQR_km) &
                    (df_clean['mileage'] <= Q3_km + 1.5*IQR_km)]

In [9]:
print("Статистическое описание числовых признаков:")
display(df_clean.describe())

Статистическое описание числовых признаков:

              year         price        mileage
count  3964.000000  3.964000e+03    3964.000000
mean   2012.954339  3.932211e+05   63019.506307
std       4.227230  2.484709e+05   36218.749583
min    1992.000000  2.000000e+04       1.000000
25%    2011.000000  2.000000e+05   35000.000000
50%    2014.000000  3.450000e+05   60000.000000
75%    2016.000000  5.500000e+05   90000.000000
max    2020.000000  1.165000e+06  172000.000000

 2.4 Оценка названий столбцов

In [10]:
# Вывести на экран названия столбцов с помощью df.columns. Выявить проблемы с названиями, если они есть. При необходимости переименовать столбцы. Если проблемы не обнаружены также дать пояснения.
display(df.columns)
display(df_clean.columns)

Index(['Name', 'year', 'SellingPrice', 'kmdriven', 'fuel', 'seller_Type',
       'transmission', 'owner'],
      dtype='object')

Index(['name', 'year', 'price', 'mileage', 'fuel', 'seller', 'transmission',
       'owner'],
      dtype='object')


---

**Сделать выводы. Вы должны понимать, что означает тот или иной столбец, чтобы
 ответить на вопросы на защите.**


 ---

### 3. Проверка пропусков

In [11]:
# Проверить данные на наличие пропусков и устранить их, если они есть (пропуски необходимо либо удалить, либо заменить каким-то значением).
print("Пропущенные значения по столбцам:\n", df.isnull().sum())

Пропущенные значения по столбцам:
 Name            0
year            0
SellingPrice    2
kmdriven        1
fuel            1
seller_Type     0
transmission    0
owner           0
dtype: int64

In [12]:
df_clean = df_clean.dropna()

In [13]:
print("Пропущенные значения по столбцам:\n", df_clean.isnull().sum())

Пропущенные значения по столбцам:
 name            0
year            0
price           0
mileage         0
fuel            0
seller          0
transmission    0
owner           0
dtype: int64


---

**Вы должны аргументировать на защите, почему были выполнены те или иные действия с пропусками, а также знать другие способы работы с пропусками, чтобы
 ответить на вопросы на защите.**


 ---

### 4. Проверка дубликатов

#### Проверка явных дубликатов

In [14]:
print(df_clean.duplicated().sum())

676

In [15]:
# удалите дубликаты, если они есть
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

#### Проверка неявных дубликатов

In [16]:
for col in df_clean.columns:
    if df_clean[col].dtype == 'object':  # только текстовые столбцы
        # приводим строки к нижнему регистру и убираем пробелы
        cleaned = df_clean[col]
        
        # получаем уникальные значения
        unique_vals = cleaned.unique()
        
        print(f"\nСтолбец '{col}' - уникальные значения:")
        print(unique_vals)

Столбец 'name' - уникальные значения:
['Maruti 800 AC' 'Maruti Wagon R LXI Minor' 'Hyundai Verna 1.6 SX' ...
 'Mahindra Verito 1.5 D6 BSIII'
 'Toyota Innova 2.5 VX (Diesel) 8 Seater BS IV'
 'Hyundai i20 Magna 1.4 CRDi']

Столбец 'fuel' - уникальные значения:
['Petrol' 'Diesel' 'Petroll' 'CNG' 'LPG' 'Electric']

Столбец 'seller' - уникальные значения:
['Individual' 'Dealer' 'Dealeer' 'Trustmark Dealer']

Столбец 'transmission' - уникальные значения:
['Manual' 'Automatic']

Столбец 'owner' - уникальные значения:
['First Owner' 'Second Owner' 'Fourth & Above Owner' 'Third Owner'
 'Test Drive Car']

In [17]:
# удалите дубликаты, если они есть
df_clean['fuel'] = df_clean['fuel'].replace('Petroll', 'Petrol')
df_clean['transmission'] = df_clean['transmission'].replace('Manual', 'Mechanics')

duplicates = ['Dealeer', 'Trustmark Dealer'] # список неправильных названий
name = 'Dealer'# правильное название
df_clean['seller'] = df_clean['seller'].replace(duplicates, name)

---

**Вы должны аргументировать на защите, почему были выполнены те или иные действия с дубликатами, знать, что такое явные и неявные дубликаты и способы работы с ними, чтобы ответить на вопросы на защите.**


 ---

### 5. Провека типов данных

In [18]:
display(df_clean.dtypes)

name             object
year              int64
price           float64
mileage         float64
fuel             object
seller           object
transmission     object
owner            object
dtype: object

In [19]:
# Проверьте типы данных, при необходимости измените типы данных, чтобы они соответствовали действительности.
df['year'] = pd.to_datetime(df['year'], format='%Y')

---

**Обратите внимание, что во всех вариантах необходимо сделать приведение типов. Будьте готовы на защите аргументировать проверку типов (почему выполнены те или иные преобразования).**


 ---

### 6. Группировка данных

#### Задание 1

*`Формулировка задания`*

In [20]:
# выполните группировку согласно варианту
# Задание 1 : Группировка - тип коробки передач (transmission) по количеству разных типов топлива (fuel)
group1 = df_clean.groupby(['transmission', 'fuel'])['fuel'].count()
display(group1)

transmission  fuel
Automatic     Diesel        64
              Electric       1
              Petrol       125
Mechanics     CNG           37
              Diesel      1478
              LPG           22
              Petrol      1561
Name: fuel, dtype: int64

**`Сделайте вывод - интерпретацию - что можно увидеть из результата данной группировки?`**

---

**Обратите внимание, что на защите вы должны ориентироваться в синтаксисе. При необходимости нужно быть готовым изменить код по просьбе преподавателя. Например, вместо среднего значения подсчитать медиану и т.д.**


 ---

#### Задание 2

In [21]:
# выполните группировку согласно варианту
#Задание 2: Группировка - тип владельца (owner) по количеству разных коробок передач (transmission). Создать датафрейм. Переименовать столбец сколичеством в “сount”. Отсортировать по убыванию столбца “count”.
group2 = df_clean.groupby(['owner', 'transmission'])['transmission'].count().reset_index(name='count').sort_values(by = 'count', ascending = False)
display(group2)

                  owner transmission  count
1           First Owner    Mechanics   1887
5          Second Owner    Mechanics    885
9           Third Owner    Mechanics    245
0           First Owner    Automatic    131
3  Fourth & Above Owner    Mechanics     68
4          Second Owner    Automatic     45
7        Test Drive Car    Mechanics     13
8           Third Owner    Automatic     11
2  Fourth & Above Owner    Automatic      2
6        Test Drive Car    Automatic      1

**`Сделайте вывод - интерпретацию - что можно увидеть из результата данной группировки?`**

---

**Обратите внимание, что на защите вы должны ориентироваться в синтаксисе. При необходимости нужно быть готовым изменить код по просьбе преподавателя. Например, вместо среднего значения подсчитать медиану и т.д.**


 ---

#### Задание 3

In [22]:
# выполните сводную таблицу согласно варианту
# Задание 3: Сводная таблица (pivot_table) - средняя стоимость для каждого года year. Отсортировать по убыванию. Округлить до трёх знаков.
pivot_year = df_clean.pivot_table(index='year', values='price', aggfunc='mean')

# Сортировка по убыванию
pivot_year = pivot_year.sort_values(by='price', ascending=False)

# Округление до 3 знаков
pivot_year = pivot_year.round(3)

display(pivot_year)

           price
year
2020  641102.513
2019  626626.828
2018  626476.339
2017  575356.865
2016  520148.802
2015  462750.741
2014  428812.037
2013  377623.801
2012  329278.437
2011  268526.263
2010  234808.631
1996  225000.000
2009  207789.441
2008  177816.089
1998  165111.111
2007  159663.627
2006  149223.518
2004  122486.083
2005  110329.466
2001  106866.600
1995   95000.000
1997   93000.000
2003   87090.909
2002   86111.111
2000   81500.000
1999   73888.889
1992   50000.000

**`Сделайте вывод - интерпретацию - что можно увидеть из результата данной сводной таблицы?`**

---

**Обратите внимание, что на защите вы должны ориентироваться в синтаксисе. При необходимости нужно быть готовым изменить код по просьбе преподавателя. Например, вместо среднего значения подсчитать медиану и т.д.**


 ---

#### Задание 4

In [23]:
# выполните сводную таблицу согласно варианту
# Задание 4: Сводная таблица (pivot_table) - среднее цена для каждого типа владельца - столбцы и типа продавца- строки. Отсортировать по возрастанию seller. Округлить до двух знаков.
pivot_seller_owner = df_clean.pivot_table(index='seller', columns='owner', values='price', aggfunc='mean')

# Сортировка по djphfcnfyb.
pivot_seller_owner = pivot_seller_owner.sort_values(by='seller', ascending=True)

# Округление до 2 знаков
pivot_seller_owner = pivot_seller_owner.round(2)

display(pivot_seller_owner)

owner,First Owner,Fourth & Above Owner,Second Owner,Test Drive Car,Third Owner
seller,,,,,
Dealer,502948.77,117499.50,395576.02,871999.79,165857.00
Individual,429639.66,177514.68,300243.62,NaN,226626.92

**`Сделайте вывод - интерпретацию - что можно увидеть из результата выполнения данного кода?`**

---

**Обратите внимание, что на защите вы должны ориентироваться в синтаксисе. При необходимости нужно быть готовым изменить код по просьбе преподавателя. Например, вместо среднего значения подсчитать медиану и т.д.**


 ---

### Вывод

В ходе выполнения лабораторной работы был проведен предварительный анализ набора данных `auto.csv`, содержащего информацию о рынке поддержанных автомобилей. Предметная область исследования - анализ характеристик б/у автомобилей и их влияния на стоимость.
На этапе предобработки данных были выполнены следующие операции:

-	Проверка данных на пропуски и дубликаты
-	Анализ и корректировка типов данных
-	 Проверка названий столбцов на соответствие

Основные результаты анализа:
-	Группировка по типу коробки передач и топливу показала, что автомобили с механической КПП преобладают над автоматическими, причем наиболее распространены бензиновые и дизельные модели.

-	Группировка по типу владельца и коробке передач выявила распределение различных типов трансмиссий среди разных категорий владельцев.
-	Сводная таблица по средней стоимости по годам продемонстрировала динамику цен на поддержанные автомобили в зависимости от года выпуска, что позволяет оценить зависимость стоимости от возраста автомобиля.
-	Сводная таблица по средней цене по типу владельца и продавца показала различия в стоимости автомобилей в зависимости от статуса владельца и типа продавца, что может быть полезно для оценки рыночной стоимости при различных условиях продажи.

Проведенный анализ позволяет сделать вывод о наличии четких зависимостей между техническими характеристиками автомобилей, их возрастом и рыночной стоимостью, что может быть использовано для прогнозирования цен и принятия решений на рынке поддержанных автомобилей.

### Дополнительное задание

**`Подробная формулировка задания`**

In [24]:
# код выполнения задания

***`Подробный вывод по заданию, описание полученных результатов`***